[project]
name = "test-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "amis-python",
    "django>=4.2.26",
]

[tool.uv.sources]
amis-python = { path = "../", editable = true }
